In [3]:
#Step 1: Import Required Libraries

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

#pandas → load dataset
#train_test_split → split data
#GaussianNB → apply Naïve Bayes

<class 'ModuleNotFoundError'>: No module named 'seaborn'

In [7]:
#Step 2: Load Dataset

data = pd.read_csv("iris.csv")

In [8]:
#Step 3: Separate Features and Target

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

#X = input features (sepal length, sepal width, etc.)
#y = output (flower type)

In [9]:
#Step 4: Split Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#70% data → training
#30% data → testing

In [10]:
#Step 5: Create Model

model = GaussianNB()

#Creates Naïve Bayes classifier for continuous data.

In [11]:
#Step 6: Train Model

model.fit(X_train, y_train)

# Model learns patterns from training data.

,priors,None
,var_smoothing,1e-09


In [13]:
#Step 7: Predict Output

y_pred = model.predict(X_test)

In [14]:
#Step 8: Generate Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

#Output is a 3×3 matrix because Iris has 3 classes.

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [2]:
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=[0,1,2], yticklabels=[0,1,2])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix Heatmap')
plt.show()

<Figure size 600x400 with 0 Axes>

<class 'NameError'>: name 'sns' is not defined

In [15]:
#Step 9: Accuracy

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

In [16]:
#Step 10: Error Rate

error_rate = 1 - accuracy

In [17]:
#Step 11: Precision

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='macro')

In [18]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred, average='macro')

In [19]:
print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)


Accuracy: 0.9777777777777777
Error Rate: 0.022222222222222254
Precision: 0.9761904761904763
Recall: 0.9743589743589745
